/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace user_service {
    // tslint:disable-next-line:no-empty-interface
    export interface Empty {
    }
    export interface UserService {
        getUsers(
            data: Empty,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<UserList>;
    }
    export interface User {
        id?: number;
        email?: string;
        userName?: string;
        password?: string;
        avatar?: string;
        dateOfBirth?: string;
        createdAt?: string;
        updatedAt?: string;
        deletedAt?: string;
    }
    export interface UserList {
        users?: user_service.User[];
    }
}

