/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace ping_pong {
    export interface PingPongService {
        pingPong(
            data: PingPongRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<PingStatus>;
    }
    export interface PingStatus {
        status?: string;
        message?: string;
    }
    export interface PingPongRequest {
        serviceName?: string;
    }
}

